# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce7a29ce5c92d449853ed5870f78fe8ccc863b3da8927aaa8d2e2c44003f68051824a9b12030f33014fb12b389e5292521e4e12acf4d35cfa971cf42ba59ed97

test:
  secret_key_base: 1fd7304740184561654de86c9280c33d065ef826af0afbb2fa7ce7af76d8d6925df9c805851b672e3aa13360f4829f5a0a86d350b8465fedfb73975adbcafc27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
